### ISSUE TITLE
Creative players can't be tagged

### ISSUE THREAD

**Issue by JelCraft** [doublehelix457/Tag#1]
When players are in creative mode, they cannot be tagged by another player. Would like to see this fixed/toggleable if possible ;)

**Comment by doublehelix457** [comment]
I'm very excited people use this plugin! Ill get on it right away. Does this need an update as well or is it working on the latest version?

**Comment by doublehelix457** [comment]
Just resolved now for 1.15. Ill be updating to newer versions now!

**Comment by JelCraft** [comment]
Awesome! Love the quick support.
